export const SCENARIO_PROMPTS: string[] = [
  // 1. Hội nghị thành lập Đảng, 1930
  "Bối cảnh: Cửu Long, Hồng Kông, tháng 2 năm 1930. Dưới sự chủ trì của lãnh tụ Nguyễn Ái Quốc, Hội nghị hợp nhất các tổ chức cộng sản đang diễn ra trong bối cảnh cực kỳ khẩn trương. Các đại biểu từ Đông Dương Cộng sản Đảng và An Nam Cộng sản Đảng vẫn còn những bất đồng sâu sắc về cương lĩnh và tên gọi của Đảng mới. Là Nguyễn Ái Quốc, bạn phải đưa ra quyết định then chốt để dung hòa các khác biệt, quy tụ lòng người và thành lập một chính đảng thống nhất, vững mạnh cho cách mạng Việt Nam.",
  // 2. Cách mạng tháng Tám, 1945
  "Bối cảnh: Tân Trào, Tuyên Quang, ngày 13 tháng 8 năm 1945. Phát xít Nhật vừa tuyên bố đầu hàng Đồng minh, tạo ra một khoảng trống quyền lực vô giá. Thời cơ 'ngàn năm có một' để giành độc lập đã đến. Tại Hội nghị toàn quốc của Đảng, không khí sục sôi. Bạn là một đồng chí trong Thường vụ Trung ương Đảng, và cuộc thảo luận đang tập trung vào việc: phát động Tổng khởi nghĩa trên toàn quốc ngay lập tức để chớp thời cơ, hay thận trọng chờ đợi quân Đồng minh vào giải giáp quân Nhật để tránh xung đột vũ trang lớn?",
  // 3. Chiến dịch Điện Biên Phủ, 1954
  "Bối cảnh: Sở chỉ huy chiến dịch Điện Biên Phủ, Mường Phăng, ngày 26 tháng 1 năm 1954. Đại tướng Võ Nguyên Giáp và Bộ chỉ huy đang đứng trước một trong những quyết định khó khăn nhất cuộc đời. Kế hoạch ban đầu là 'đánh nhanh, thắng nhanh'. Tuy nhiên, sau khi trinh sát, nhận thấy địch đã xây dựng tập đoàn cứ điểm cực kỳ kiên cố. Thay đổi phương châm sang 'đánh chắc, tiến chắc' sẽ kéo dài thời gian, gây áp lực khủng khiếp về hậu cần và có thể làm giảm nhuệ khí bộ đội, nhưng đảm bảo thắng lợi cao hơn. Giữ nguyên kế hoạch có thể tạo bất ngờ nhưng rủi ro thất bại là rất lớn.",
  // 4. Thống nhất đất nước và kinh tế, 1976
  "Bối cảnh: Hà Nội, năm 1976, ngay sau khi đất nước thống nhất về mặt nhà nước. Đại hội Đảng toàn quốc lần thứ IV đang được chuẩn bị. Vấn đề nóng bỏng nhất là mô hình kinh tế cho cả nước. Miền Bắc đã có kinh nghiệm với kinh tế kế hoạch hóa tập trung. Miền Nam lại có nền kinh tế thị trường và sở hữu tư nhân phát triển. Là một nhà hoạch định chính sách, bạn sẽ đề xuất phương án nào: áp dụng mô hình kinh tế kế hoạch hóa tập trung, bao cấp trên toàn quốc để đảm bảo sự đồng nhất, hay cho phép một mô hình kinh tế quá độ với nhiều thành phần, thừa nhận kinh tế tư nhân ở miền Nam?",
  // 5. Trước thềm Đổi Mới, 1986
  "Bối cảnh: Hà Nội, tháng 12 năm 1986. Đất nước đang trong khủng hoảng kinh tế - xã hội trầm trọng. Mô hình kế hoạch hóa tập trung quan liêu, bao cấp đã bộc lộ những khuyết điểm nghiêm trọng, đời sống nhân dân hết sức khó khăn. Trước thềm Đại hội Đảng lần thứ VI, các luồng tư tưởng đang tranh cãi gay gắt. Là một ủy viên Bộ Chính trị có tư tưởng cấp tiến, bạn phải đưa ra quan điểm dứt khoát: tiếp tục kiên định với mô hình cũ và tìm cách tháo gỡ khó khăn, hay dũng cảm đề xuất một cuộc 'Đổi Mới' toàn diện, chấp nhận kinh tế thị trường có sự quản lý của nhà nước và xóa bỏ cơ chế bao cấp?"
];
